
List<Map> cars = [

  {
    'carName': 'Hyundai Verana 2024',
    'carClass': 'City',
    'carPower': 111,
    'people': '1-4',
    'bags': '1-2',
    'carImage': 'assets/images/verana.png',
    'carPrice': 10,
    'isRotated': false,
    'carRating': '3.7',
  },
  {
    'carName': 'Hyundai Creta 2024',
    'carClass': 'City',
    'carPower': 157,
    'people': '1-4',
    'bags': '1-2',
    'carImage': 'assets/images/Hyundai_creta.jpg',
    'carPrice': 20,
    'isRotated': false,
    'carRating': '3.2',
  },
  {
    'carName': 'Skoda Slavia 2024',
    'carClass': 'City',
    'carPower': 147,
    'people': '1-4',
    'bags': '1-2',
    'carImage': 'assets/images/slavia.webp',
    'carPrice': 17,
    'isRotated': false,
    'carRating': '3.8',
  },
  {
    'carName': 'Golf R-Line 2024',
    'carClass': 'City',
    'carPower': 315,
    'people': '1-4',
    'bags': '1-2',
    'carImage': 'assets/images/golf.png',
    'carPrice': 17,
    'isRotated': false,
    'carRating': '3.8',
  },

  {
    'carName': 'Toyota Fortuner',
    'carClass': 'City',
    'carPower': 201,
    'people': '1-7',
    'bags': '1-5',
    'carImage': 'assets/images/Toyota_fortuner.webp',
    'carPrice': 35,
    'isRotated': false,
    'carRating': '4.5',
  },

  {
    'carName': 'BMW M340i',
    'carClass': 'City',
    'carPower': 275,
    'people': '1-4',
    'bags': '1-3',
    'carImage': 'assets/images/BMW_m340i.webp',
    'carPrice': 75,
    'isRotated': false,
    'carRating': '4.1',
  },
  {
    'carName': 'Audi A4',
    'carClass': 'City',
    'carPower': 187,
    'people': '1-4',
    'bags': '1-2',
    'carImage': 'assets/images/Audi_A4.webp',
    'carPrice': 47,
    'isRotated': false,
    'carRating': '4.3',
  },
  {
    'carName': 'Volvo S90',
    'carClass': 'City',
    'carPower': 246,
    'people': '1-4',
    'bags': '1-2',
    'carImage': 'assets/images/Volvo_s90.webp',
    'carPrice': 70,
    'isRotated': false,
    'carRating': '4.9',
  },
  {
    'carName': 'Mahindra Thar',
    'carClass': 'City',
    'carPower': 130,
    'people': '1-4',
    'bags': '1-2',
    'carImage': 'assets/images/thar-exterior-right-front-three-quarter-35.webp',
    'carPrice': 14,
    'isRotated': false,
    'carRating': '5.0',
  },
];
